Update terraform.yml

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -42,38 +42,38 @@ jobs:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       id: plan
-#       if: github.event_name == 'pull_request'
+      if: github.event_name == 'pull_request'
       run: terraform plan -no-color -input=false
       continue-on-error: true
       
-    - name: add-plan-comment
-      id: comment
-      uses: actions/github-script@v6.1.0
-#       if: github.event_name == 'pull_request'
-      env:
-        PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
-      with:
-        github-token: ${{ secrets.GITHUB_TOKEN }}
-        script: |
-                  const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
-                  #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
-                  #### Terraform Validation 🤖${{ steps.validate.outputs.stdout }}
-                  #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+#     - name: add-plan-comment
+#       id: comment
+#       uses: actions/github-script@v6.1.0
+# #       if: github.event_name == 'pull_request'
+#       env:
+#         PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
+#       with:
+#         github-token: ${{ secrets.GITHUB_TOKEN }}
+#         script: |
+#                   const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
+#                   #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+#                   #### Terraform Validation 🤖${{ steps.validate.outputs.stdout }}
+#                   #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
 
-                  <details><summary>Show Plan</summary>
+#                   <details><summary>Show Plan</summary>
 
-                  \`\`\`${process.env.PLAN}\`\`\`
+#                   \`\`\`${process.env.PLAN}\`\`\`
           
-                  </details>
+#                   </details>
 
-                  *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
+#                   *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
 
-                  github.issues.createComment({
-                    issue_number: context.issue.number,
-                    owner: context.repo.owner,
-                    repo: context.repo.repo,
-                    body: output
-                  })
+#                   github.issues.createComment({
+#                     issue_number: context.issue.number,
+#                     owner: context.repo.owner,
+#                     repo: context.repo.repo,
+#                     body: output
+#                   })
       
       
       
@@ -107,14 +107,14 @@ jobs:
 #             body: output
 #           })
           
-    - name: Terraform Plan Status
-      if: steps.plan.outcome == 'failure'
-      run: exit 1
+#     - name: Terraform Plan Status
+#       if: steps.plan.outcome == 'failure'
+#       run: exit 1
       
-    - name: Terraform Apply
-      env:
-        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
-        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-      run: terraform apply -auto-approve -input=false
+#     - name: Terraform Apply
+#       env:
+#         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
+#         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#       if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+#       run: terraform apply -auto-approve -input=false
       
